---

- name: check connectivity to 8.8.8.8
  hosts: ios
  
  tasks:
    - ios_command: 
        commands: ping 8.8.8.8
        provider: "{{cli}}"
        wait_for:
        - result[0] contains "!!!"
      register: result
      failed_when: "not '!!!' in result.stdout[0]"

