---
- hosts: csr
  tasks:
  - ios_command:
      commands: show arp
      host:     "{{inventory_hostname}}"
      provider: "{{cli}}"
    notify: test 
  
  handlers:
    - name: test
      raw: "show hostname"
