---

- name: Upgrade a Cisco IOS router
  hosts: ios

  tasks:
   - ntc_reboot:
      platform: cisco_ios_ssh
      confirm: true
      timer: 2
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
