---

- name: Upgrade a Cisco IOS router
  hosts: ios

  tasks:
  - ios_facts:
       gather_subset: all
       #commands: show ver
       provider: "{{cli}}" 
       host: "{{inventory_hostname}}"
    
  - when: ansible_net_version != "15.5(2)S"
    ios_command:
       commands:
         - "reload\ny"
       provider: "{{cli}}"
       host: "{{inventory_hostname}}"
    register: result
     
